<a href="https://colab.research.google.com/github/Aflah3100/Numpy-Tutorial/blob/main/NumpyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
myPythonList = [1,9,8,3]
print(myPythonList)

[1, 9, 8, 3]


In [ ]:
numpy_array_from_list = np.array(myPythonList)
numpy_array_from_list


array([1, 9, 8, 3])

In [ ]:
a  = np.array([1,9,8,3])
print(a)


[1 9 8 3]


In [ ]:
x=numpy_array_from_list + 10
print(x)

[11 19 18 13]


In [ ]:
a  = np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int64


In [ ]:
b  = np.array([1.1,2.0,3.2])
print(b.dtype)

float64


In [ ]:
c = np.array([(1,2,3),
              (4,5,6)])
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
    [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)
(2, 2, 3)

(2, 2, 3)


(2, 2, 3)

In [ ]:
x=np.zeros((2,2), dtype=np.int16)
print(x)

[[0 0]
 [0 0]]


In [ ]:
np.ones((1,2,3), dtype=np.int16)

array([[[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [ ]:
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
e.flatten()


array([1, 2, 3, 4, 5, 6])

In [ ]:
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [ ]:
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


In [ ]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[4.81318237 5.60845922 5.32472935 4.95362184 4.71741987 5.28177796
 5.33910078 5.01407333 5.4168951  5.92518688]


In [ ]:
A = np.matrix(np.ones((4,4)))		
np.array(A)[2]=2  #immutable
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


In [ ]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
import numpy as np
np.linspace(1.0, 10.0, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [ ]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [ ]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize	

16

In [ ]:
e  = np.array([(1,2,3), (4,5,6)])
print(e)

[[1 2 3]
 [4 5 6]]


In [ ]:
print('First row:', e[0])


print('Second row:', e[1])

First row: [1 2 3]
Second row: [4 5 6]


In [ ]:
print('Second column:', e[:,1])	

Second column: [2 5]


In [ ]:
print(e[1, :2])

[4 5]


In [ ]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)	

[4.75830329 4.9521168  5.3612821  4.94722952 4.19345559 4.96430021
 5.3179176  5.17347064 4.90426117 5.42316463]


In [ ]:
print(np.min(normal_array))


print(np.max(normal_array))
 
print(np.mean(normal_array))

print(np.median(normal_array))

print(np.std(normal_array))

4.193455592512979
5.423164629145826
4.999550156743804
4.9582085075897595
0.3413508181880522


In [ ]:
f = np.array([1,2])
g = np.array([4,5])

np.dot(f, g)

14

In [ ]:
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 

np.matmul(h, i)


array([[19, 22],
       [43, 50]])

In [ ]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])


print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [ ]:
n_array = np.array([[50, 29], [30, 44]])
  

print("Numpy Matrix is:")
print(n_array)
  

det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330


In [ ]:

mx = np.array([[1,1,1],[0,1,2],[1,5,3]])


np.linalg.matrix_rank(mx)

3

In [ ]:
example_matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00 -5.14138333e-16 -2.08943529e-15] [[-0.15115432 -0.72704996  0.01790738 -0.26832672]
 [-0.34923733 -0.28320876  0.38415354  0.71367217]
 [-0.54732033  0.16063243 -0.82202921 -0.62236419]
 [-0.74540333  0.60447363  0.41996829  0.17701873]]


In [ ]:

gfg = np.matrix('[6, 2; 3, 4]')

diag = gfg.diagonal()
   
print(diag)

[[6 4]]


In [ ]:

gfg = np.matrix('[4, 1; 12, 3]')
              

trans = gfg.transpose()
    
print(trans)

[[ 4 12]
 [ 1  3]]


In [ ]:

gfg = np.matrix('[4, 1; 12, 3]')
              

tracem = gfg.trace()
    
print(tracem)

[[7]]
