<a href="https://colab.research.google.com/github/Aflah3100/Numpy-Tutorial/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

                                              Python Numpy 

In [ ]:
import numpy as np

                                        Creating arrays using numpy

In [ ]:
#Creating 1-d array 
nums=np.array([1,2,3,4,5])

print("Elements in array are: ")

for x in nums:
    print(x,end="  ")

Elements in array are: 
1  2  3  4  5  

In [ ]:
#Creating 2-d array
nums=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print("The elements in the 2-d array are: ")
for x in range(0,3,1):
    for y in range(0,3,1):
        print(nums[x,y],end="\t")
    print("\n")

The elements in the 2-d array are: 
1	2	3	

4	5	6	

7	8	9	



In [ ]:
#Array operations in numpy

num1=np.array([1,2,3])
num2=np.array([4,5,6])

add=num1+num2
sub=num1-num2
mul=num1*num2
div=num1/num2

print("Added array: "+str(add)+"\nSubtracted array: "+str(sub)+"\nMultiplied array: "+str(mul)+"\nDivided array: "+str(div))

Added array: [5 7 9]
Subtracted array: [-3 -3 -3]
Multiplied array: [ 4 10 18]
Divided array: [0.25 0.4  0.5 ]


In [ ]:
#Creating array using arange
nums=np.arange(1,11,1)

print("Numbers in array are: ")

for x in nums:
    print(x,end="  ")

Numbers in array are: 
1  2  3  4  5  6  7  8  9  10  

In [ ]:
#Creating array using linspace
nums=np.linspace(1,11,11)

print("Numbers in array are: ")

for x in nums:
    print(int(x),end="  ")

Numbers in array are: 
1  2  3  4  5  6  7  8  9  10  11  

In [ ]:
#Creating array using logspace

nums=np.logspace(1,10,10)

for x in nums:
    print(x,end="  ")

10.0  100.0  1000.0  10000.0  100000.0  1000000.0  10000000.0  100000000.0  1000000000.0  10000000000.0  

In [ ]:
#creating array using zeroes 

zeroarray=np.zeros((2,3),dtype=np.int32)

print("Array: ")

for x in range(0,2,1):
    for y in range(0,3,1):
        print(zeroarray[x,y],end="\t")
    print("\n")

Array: 
0	0	0	

0	0	0	



In [ ]:
#Creating array using ones

onearray=np.ones((2,3),dtype=np.int32)

print("Numbers in array are: ")

for x in range(0,2,1):
    for y in range(0,3,1):
        print(onearray[x,y],end="\t")
    print("\n")

Numbers in array are: 
1	1	1	

1	1	1	



In [ ]:
#Reshaping the array

nums=np.array([
    [1,2,3],
    [7,8,9],
])

nums.reshape(3,2)

print(nums)



[[1 2 3]
 [7 8 9]]


In [ ]:
#Flattening the array

num1=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Actual array : ")

print(nums)

print("Flattened array: ")
print(nums.flatten())



Actual array : 
[[1 2 3]
 [7 8 9]]
Flattened array: 
[1 2 3 7 8 9]


In [ ]:
num1=np.array([1,2,3])
num2=np.array([4,5,6])
#Concatinating num1 and num2 horizontally and vertically

print("Horizontally concatinated array: ")

print(np.hstack((num1,num2)))

print("Vertically concatinated array: ")
print(np.vstack((num1,num2)))


Horizontally concatinated array: 
[1 2 3 4 5 6]
Vertically concatinated array: 
[[1 2 3]
 [4 5 6]]


In [ ]:
#Random number generator 

nums=np.random.normal(10,4,5)
print("Random numbers are: ")
for x in nums:
    print(x,end="  ")

print("\n")

num2=np.random.randint(100,size=(1,5))


print("Random numbers generated are: ")

for x in range(0,1,1):
    for y in range(0,5,1):
        print(num2[x,y],end="  ")
    print("\n")

Random numbers are: 
8.12324864764884  6.094397300017059  6.1827878758917825  11.395483557803768  5.9258499893835666  

Random numbers generated are: 
41  70  79  75  60  



In [ ]:
#Slicing arrays

numbers=np.array([
    [1,2,3,5],
    [4,5,6,7],
    [8,9,10,11],
    [12,13,14,15]
])

print("First row: "+str(numbers[0]))

print("First column : "+str(numbers[:,0]))

print("Last 2 rows: "+str(numbers[2:4]))

print("First 3 numbers in 2nd row "+str(numbers[1,0:3:1]))

First row: [1 2 3 5]
First column : [ 1  4  8 12]
Last 2 rows: [[ 8  9 10 11]
 [12 13 14 15]]
First 3 numbers in 2nd row [4 5 6]


In [ ]:
numbers=np.array([1,2,3,10,111,18])

#Maximum number 

print("Maximum number in the array: "+str(np.max(numbers)))

#Minimum number

print("Minimum number in the array: "+str(np.min(numbers)))

#Mean of the array

print("Mean of the numbers in the array : "+str(np.mean(numbers)))

#Median of the array

print("Median of the numbers in the array: "+str(np.mean(numbers)))

#Standard deviation of the array

print("Stadard deviation of the numbers in the array: "+str(np.std(numbers)))

Maximum number in the array: 111
Minimum number in the array: 1
Mean of the numbers in the array : 24.166666666666668
Median of the numbers in the array: 24.166666666666668
Stadard deviation of the numbers in the array: 39.274320136982915


                                                  Creating Matrix

In [ ]:
matrix1=np.matrix('1,2,3;4,5,6;7,8,9')

print("Matrix1: \n"+str(matrix1))

matris2=np.matrix(np.zeros((3,3),dtype=np.int32))

print("Matrix2: \n"+str(matris2))

Matrix1: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix2: 
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
matrix1=np.matrix('1,2,3;4,5,6;7,8,9')

print("Matrix1: \n"+str(matrix1))

#Finding the diagnol of the matrix

print("Diagnol: "+str(matrix1.diagonal()))

#Trace of the matrix:

print("Trace: "+str(matrix1.trace()))

#Transpose

print("Transpose:\n "+str(matrix.transpose()))

Matrix1: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagnol: [[1 5 9]]
Trace: [[15]]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#Finding dot product of 2 arrays

num1=np.array([1,2,4])
num2=np.array([4,5,6])

result=np.dot(num1,num2)

print("Dot product: "+str(result))

Dot product: 38


In [ ]:
#Matrix multiplication of 2 arrays

num1=np.array([
    [1,2,1],
    [3,4,5]

])

num2=np.array([
    [5,6],
    [7,8],
    [9,10]
])

print("Matrix Multiplication : \n"+str(np.matmul(num1,num2)))

Matrix Multiplication : 
[[ 28  32]
 [ 88 100]]


In [ ]:
num1=np.array([
    [10,11,12],
    [13,14,15],
    [16,17,29]
])

#Finding the Determinant
print("Determinant: "+str(np.linalg.det(num1)))

#Finding the inverse

print("Inverse:\n"+str(np.linalg.inv(num1)))

#Rank of the matrix

print("Rank: "+str(np.linalg.matrix_rank(num1)))

#eigen values and eigen vector

eigvalue,eigvector=np.linalg.eig(num1)

print("Eigenvalue: "+str(eigvalue))

print("Eigen vector:\n"+str(eigvector))





Determinant: -33.0
Inverse:
[[-4.57575758  3.48484848  0.09090909]
 [ 4.15151515 -2.96969697 -0.18181818]
 [ 0.09090909 -0.18181818  0.09090909]]
Rank: 3
Eigenvalue: [47.84385758 -0.13046989  5.28661231]
Eigen vector:
[[-0.39001187 -0.74844014 -0.41394214]
 [-0.49417294  0.66275664 -0.5842043 ]
 [-0.77697095  0.02431061  0.69810976]]
